version: 2.0
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:8.0.242-node
      - image: kylemanna/bitcoind:latest
        name: bitcoind01
        environment:
          DISABLEWALLET: 0
        command: [ "-printtoconsole", "-regtest", "-debug",
          "-server", "-listen", "-port=31591", "-connect=bitcoind02:31592",
          "-rpcbind=0.0.0.0:32591", "-rpcallowip=0.0.0.0/0",
          "-rpcuser=admin", "-rpcpassword=admin"]

      - image: kylemanna/bitcoind:latest
        name: bitcoind02
        environment:
          DISABLEWALLET: 0
        command: [ "-printtoconsole", "-regtest", "-debug",
          "-server", "-listen", "-port=31592", "-connect=bitcoind01:31591",
          "-rpcbind=0.0.0.0:32591", "-rpcallowip=0.0.0.0/0",
          "-rpcuser=admin", "-rpcpassword=admin" ]

    working_directory: ~/tmp

    steps:
      - checkout

      - run:
          name: Clone RSKj
          command: |
            if [ -n "$RSKJ_PR_NUMBER" ]; then # target is PR against rsksmart/rskj
              git clone "https://github.com/$RSKJ_CIRCLE_USERNAME/$RSKJ_CIRCLE_REPONAME" ~/rsksmart/rskj
              cd ~/rsksmart/rskj/
              git fetch origin +refs/pull/"$RSKJ_PR_NUMBER"/merge
              git checkout FETCH_HEAD
            else # target is a push against rsksmart/rskj
              git clone --branch "$RSKJ_CIRCLE_BRANCH" --single-branch "https://github.com/$RSKJ_CIRCLE_USERNAME/$RSKJ_CIRCLE_REPONAME" ~/rsksmart/rskj
              if [ -n "$RSKJ_CIRCLE_SHA1" ]; then
                cd ~/rsksmart/rskj/
                git checkout "$RSKJ_CIRCLE_SHA1"
              fi
            fi
      - run:
          name: Build RSKj
          command: |
            cd ~/rsksmart/rskj/
            ./configure.sh
            ./gradlew clean build -x test

      - run:
          name: Start RskJ & Run Tests
          command: |
            npm install
            node generateBtcBlocks.js  
            version=$(tr -d "'\"" <~/rsksmart/rskj/rskj-core/src/main/resources/version.properties \
              | cut -d = -f 2- | paste -sd - -)
            java -Drsk.conf.file=./rsk-integration-test.conf -cp ~/rsksmart/rskj/rskj-core/build/libs/rskj-core-"$version"-all.jar co.rsk.Start --regtest & rskpid=$!
            until nc -z 127.0.0.1 4444
            do
              echo "Waiting for RskJ..."
              sleep 1
            done
            npm test
            kill $rskpid
            
      - store_test_results:
          path: ~/tmp/Results
      
      - store_artifacts:
          path: ~/tmp/Results/mocha
          
      - store_artifacts:
          path: ~/tmp/logs